theme: jekyll-theme-cayman

<!DOCTYPE html>
<html lang="zh_CN">
<head>
  <title>hello，我是小彭鸭</title>
</head>
<body>
  <p align="center"><font size="7" color="#0000ff">嘿嘿！</font></p>
  <p align="center"><font size="5" color="#0000ff">XiaoPeng</font></p>
  <p align="center"><font size="7" color="#0000ff">窝窝头</font></p>
  <p align="center"><font size="7" color="#0000ff">一块钱四个</font></p>
  <p align="center"><font size="7" color="#0000ff">嘿嘿！</font></p>
  <p align="center"><font size="7" color="#0000ff">嘿！</font></p>
  <p align="center"><font size="7" color="#0000ff">！</font></p>
  <p align="center"><font size="7" color="#0000ff">是的是的</font></p>
  <p align="center"><font size="7" color="#0000ff">我是小彭</font></p>
  <p align="center"><font size="7" color="#0000ff">这是我做的第一个网页</font></p>
  <p align="center"><font size="7" color="#0000ff">如果我让你打开它</font></p>
  <p align="center"><font size="7" color="#0000ff">祝你天天开心鸭！</font></p>
  <p align="center"><font size="7" color="#0000ff">小彭2020.01.09</font></p>
</body>
</html>
